# Generated by Django 4.2.28 on 2026-02-19 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target_role', models.CharField(blank=True, default='', max_length=120)),
                ('ats_score', models.PositiveSmallIntegerField()),
                ('role_match_score', models.PositiveSmallIntegerField()),
                ('keyword_coverage', models.FloatField()),
                ('resume_hash', models.CharField(db_index=True, max_length=64)),
                ('jd_hash', models.CharField(db_index=True, max_length=64)),
                ('payload', models.JSONField()),
            ],
            options={
                'indexes': [models.Index(fields=['created_at'], name='ats_engine__created_ed77d1_idx'), models.Index(fields=['resume_hash', 'jd_hash'], name='ats_engine__resume__eb8729_idx')],
            },
        ),
    ]
