# Generated by Django 4.2.7 on 2026-04-26 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata_app', '0002_biodatatemplate_remove_biodata_dob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biodata',
            name='generated_pdf_key',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
