# Generated by Django 4.2.7 on 2026-04-09 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('visiting_card_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitingCardTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(blank=True, null=True, upload_to='visiting_card_templates/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='visiting_card_thumbnails/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='visitingcard',
            name='address',
        ),
        migrations.RemoveField(
            model_name='visitingcard',
            name='company',
        ),
        migrations.RemoveField(
            model_name='visitingcard',
            name='name',
        ),
        migrations.RemoveField(
            model_name='visitingcard',
            name='template_type',
        ),
        migrations.AddField(
            model_name='visitingcard',
            name='additional_fields',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='visitingcard',
            name='card_for',
            field=models.CharField(default='Individual', max_length=50),
        ),
        migrations.AddField(
            model_name='visitingcard',
            name='card_type',
            field=models.CharField(default='Single side', max_length=50),
        ),
        migrations.AddField(
            model_name='visitingcard',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='visitingcard',
            name='company_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='visitingcard',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='visitingcard',
            name='company_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='visitingcard',
            name='company_website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitingcard',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visitingcard',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='visitingcard',
            name='full_name',
            field=models.CharField(default='unknown', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visitingcard',
            name='generated_pdf_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='visitingcard',
            name='language',
            field=models.CharField(default='English', max_length=50),
        ),
        migrations.AddField(
            model_name='visitingcard',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='visiting_cards/logos/'),
        ),
        migrations.AddField(
            model_name='visitingcard',
            name='pincode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='visitingcard',
            name='slogan',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='visitingcard',
            name='street',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='visitingcard',
            name='template_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='visitingcard',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='visitingcard',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visiting_cards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='visitingcard',
            name='designation',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='visitingcard',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='VisitingCardTemplateSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_by', to='visiting_card_app.visitingcardtemplate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visiting_card_template_selections', to=settings.AUTH_USER_MODEL)),
                ('visiting_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visiting_card_app.visitingcard')),
            ],
            options={
                'unique_together': {('visiting_card',)},
            },
        ),
    ]
