# Generated by Django 4.2.7 on 2026-04-09 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('visiting_card_app', '0002_visitingcardtemplate_remove_visitingcard_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitingcardtemplateselection',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visiting_card_template_selections', to=settings.AUTH_USER_MODEL),
        ),
    ]
