# Generated by Django 4.2.7 on 2026-04-14 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visiting_card_app', '0003_alter_visitingcardtemplateselection_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitingcard',
            name='generated_pdf_key',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
