# Generated by Django 4.2.7 on 2026-04-19 05:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('biodata_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiodataTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='biodata_templates/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='biodata_thumbnails/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='biodata',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='biodata',
            name='education',
        ),
        migrations.RemoveField(
            model_name='biodata',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='biodata',
            name='occupation',
        ),
        migrations.RemoveField(
            model_name='biodata',
            name='preferences',
        ),
        migrations.RemoveField(
            model_name='biodata',
            name='template_type',
        ),
        migrations.AddField(
            model_name='biodata',
            name='birth_details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='biodata',
            name='contact_details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='biodata',
            name='family_details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='biodata',
            name='generated_pdf_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='biodata',
            name='language',
            field=models.CharField(default='English', max_length=50),
        ),
        migrations.AddField(
            model_name='biodata',
            name='personal_details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='biodata',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='biodata/photos/'),
        ),
        migrations.AddField(
            model_name='biodata',
            name='template_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='biodata',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='biodata',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='biodatas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='BiodataTemplateSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_at', models.DateTimeField(auto_now_add=True)),
                ('biodata', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='biodata_app.biodata')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_by', to='biodata_app.biodatatemplate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biodata_template_selections', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
