# Generated by Django 4.2.7 on 2026-03-02 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_signupotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupotp',
            name='full_name',
            field=models.CharField(default='unknown', max_length=200),
            preserve_default=False,
        ),
    ]
