# Generated by Django 4.2.7 on 2026-03-02 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0005_signupotp_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupotp',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
