# Generated by Django 4.2.7 on 2026-02-15 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='resumetemplateselection',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='resumetemplateselection',
            name='resume',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='resume_app.resume'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='resumetemplateselection',
            unique_together={('resume',)},
        ),
    ]
