# Generated by Django 4.2.7 on 2026-03-18 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0002_alter_resumetemplateselection_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='generated_resume_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
