# Generated by Django 4.2.11 on 2026-01-07 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0002_remove_resume_experience_resume_accomplishments_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resume',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='resume',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
