# Generated by Django 4.2.11 on 2026-01-07 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resume_app', '0003_alter_resume_options_resume_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='accomplishments',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='company',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='degree',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='description',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='edu_location',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='hobbies',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='job_title',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='languages',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='location',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='score',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='year_of_completion',
        ),
        migrations.AddField(
            model_name='resume',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='resume_app.resume')),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=100)),
                ('institution', models.CharField(max_length=150)),
                ('year_of_completion', models.IntegerField(blank=True, null=True)),
                ('score', models.CharField(blank=True, max_length=20, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='resume_app.resume')),
            ],
            options={
                'ordering': ['-year_of_completion'],
            },
        ),
    ]
